CPUTIME9 RSECT
CPUTIME9 AMODE 31
CPUTIME9 RMODE ANY
*  GET CURRENT CPU USAGE IN MICROSECONDS.
*  BY DAVID STAUDACHER
*     CALL W-CPUTIME9 USING  9(12)V9(6) COMP-5 <== SECS V MICROSECS
       PRINT   GEN
       SAVE    (14,2)  ONLY SAVE REGS WE ACTUALLY USE
       L       2,0(,1)  R2 -> 8 BYTE AREA TO RECEIVE CPU TIME USED
       TIMEUSED STORADR=(2),ECT=YES
       LG      0,0(,2)  R0 = RESULT IN TOD FORMAT
       SRLG    0,0,12  R0 = RESULT IN MIC FORMAT
       STG     0,0(,2)  RETURN MIC FORMAT RESULT
       RETURN  (14,2),RC=(15)
*
       CVT     DSECT=YES,LIST=NO
       IHAECVT DSECT=YES,LIST=YES
       IHAPSA
       END
